### ISSUE TITLE
[market.js] Refactor to use the latest version of MARKET.js

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKET.js#117]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a dev, I need to refactor market-api so that is works with the latest refactor of market.js.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Get market-api to work with the latest version of MARKET.js

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Implement the latest version of MARKET.js in market-api.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
market-api works with the `^0.2.0` version of MARKET.js.

**Comment by perfectmak** [comment]
@rojosnow shouldn't this be in the [market-api ](https://github.com/MARKETProtocol/market-api) repository or maybe I'm clear of the description?

**Comment by rojosnow** [comment]
Issue moved to [MARKETProtocol/market-api #33](https://github.com/MARKETProtocol/market-api/issues/33) via [**ZenHub**](https://www.zenhub.com/)

**Comment by rojosnow** [comment]
@perfectmak Thanks for the heads up!
