### ISSUE TITLE
Add generated docs to .gitignore

### ISSUE THREAD

**Issue by cryptomental** [MARKETProtocol/MARKET.js#119]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

As a developer, I want to have generated documentation ignored by GIT.

### Why Is this Needed?

Dev workflow.

### Current Behavior
Generated docs are not ignored by GIT.

### Expected Behavior
Generated docs are ignored by GIT.

**Comment by cryptomental** [comment]
Self-assigned

**Comment by eswarasai** [comment]
@cryptomental -- I've recently removed the `docs` from the `.gitignore` the reason being we need the auto-generated `docs` to be hosted somewhere and as part of it, I've done that change as per requested by @rojosnow. I'm not sure at the moment, what would be the best way, probably have the docs generated at the time of release and push to AWS S3 bucket maybe which can be self-hosted on one of the sub-domains. But for the time-being, will let `docs` stay within the GitHub repo until we figure out a plan for this. Please do let me know your thoughts on this. Thanks!

**Comment by cryptomental** [comment]
@eswarasai ok thanks for the explanation. I had issues with commits and was forced to pass --no-verify to avoid docs/ being added to a commit. They are always added after you run prod test in the docker container and then git commit your changes. If as you said docs will be moved somewhere else we can void this PR.

**Comment by cryptomental** [comment]
Closing as won't do.

**Comment by pelsasser** [comment]
We can add them to .gitignore but still have them be under version control, that way when we prepare a release we can explicitly commit them, but otherwise it will be ignored while under normal dev workflow.

**Comment by eswarasai** [comment]
@pelsasser -- For the time being, I've added the `docs` to `.gitignore` and tracking the deployment/release of the `docs` for `MARKET.js` here -- https://github.com/MARKETProtocol/MARKET.js/issues/105
