### ISSUE TITLE
ContractSet#getContractMetaDataAsync missing isWhitelisted and collateralTokenName

### ISSUE THREAD

**Issue by dmvt** [MARKETProtocol/MARKET.js#122]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want to receive metadata for the contract which includes `isWhitelisted` and `collateralTokenName` so that I can submit a fully valid response to the API `contracts` endpoint.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: The `market-api` `contracts` object is only considered valid if if has values for both of these fields. At the moment, I'm hard coding `isWhitelisted` to `true` and `collateralTokenName` to `'Not Available'`.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug / Missing Functionality

### Current Behavior
[comment]: # (Describe what actually happened.)
These values are missing from the returned object.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
These values should be returned along with the rest of the contract metadata.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
`marketjs.getContractMetaDataAsync(address)`

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Add these values to the return of `ContractSet#getContractMetaDataAsync`

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] When called, `ContractSet#getContractMetaDataAsync` returns an object which includes a boolean value for `isWhitelisted` and a string value for `collateralTokenName`

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Result should include all values required to satisfy https://github.com/MARKETProtocol/market-api/blob/feature/postgres-db/src/schemas/ContractsSchema.ts

**Comment by eswarasai** [comment]
@travisdmathis -- FYI -- https://github.com/MARKETProtocol/MARKET.js/blob/develop/src/contract_wrappers/ContractSet.ts#L50

**Comment by travisdmathis** [comment]
Unneeded, closing issue.
