### ISSUE TITLE
[BUG] eth.getTransaction should be a callback function in tradeOrderAsync

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/MARKET.js#125]
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Blocking bug for fill orders

### Description
https://github.com/MARKETProtocol/MARKET.js/blob/develop/src/contract_wrappers/ContractWrapper.ts#L256

This function should be a callback function.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 

### Current Behavior
[comment]: # (Describe what actually happened.)
Uncaught (in promise) Error: The MetaMask Web3 object does not support synchronous methods like eth_getTransactionByHash without a callback parameter. See https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#dizzy-all-async---think-of-metamask-as-a-light-client for details.
    at MetamaskInpageProvider.send (inpage.js:1)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
https://github.com/MARKETProtocol/MARKET.js/blob/develop/src/contract_wrappers/ContractWrapper.ts#L333

Example of how it should be used to prevent this error.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Add callback function

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Can trade order

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by rojosnow** [comment]
@travisdmathis @eswarasai Are we GTG here? It shows the PR is merged.
