### ISSUE TITLE
Expose a getBalanceAsync() function

### ISSUE THREAD

**Issue by perfectmak** [MARKETProtocol/MARKET.js#128]
### User Story
As a user of the MarketJS library, I would want a convenience function to easily a users balance for a particular token.

### Why Is this Needed?

There are many use cases where a client (d)App would like to check how much of a particular collateral or market token a user. 
The only similar function exposed by MarketJS right now is `getUserAccountBalance()` and it is used to check how much collateral has been deposited by a user to the collateral pool.

So a more aptly named function like `getBalanceAsync()` should be created to make this easy.

### Description

*Type*: Feature

### Solution

*Summary*: `getBalanceAsync()` inside the ContractWrapper should be exposed via the Market class and it should have a signature similar signature to `getBalanceAsync(tokenAddress: string, userAddress: string): Promise<BigNumber>`.

### Definition of Done

- [ ] `getBalanceAsync()` in exposed via MarketJS.
- [ ] Exposed function should have relevant tests.

**Comment by pelsasser** [comment]
@perfectmak - thanks for opening the issue!

https://github.com/MARKETProtocol/MARKET.js/blob/362b8328fa45595622f751e964361c4b17e064cf/src/contract_wrappers/ContractWrapper.ts#L729 

Has the needed functionality, but perhaps we aren't exposing it in a way you would expect?  Perhaps moving it to Market.ts would resolve some of the issue?

**Comment by perfectmak** [comment]
Yeah, I know about the function in ContractWrapper @pelsasser. This issue
was to formalize these task as a follow up to a discussion with
@travisdmathis where it would have been good to expose such functionality
in MarketJS.

And yes, the solution would be to move it to `Market.ts`. I'll update the
issue description to exposing `getBalanceAsync()` and probably submit a PR
for it too.

**Comment by pelsasser** [comment]
you guys rock, thanks!

**Comment by perfectmak** [comment]
@pelsasser, I already submitted a (tiny) PR for this issue here #130.

cc @travisdmathis perhaps when this is closed we can create an issue to update the dApp to use this function?

**Comment by travisdmathis** [comment]
@perfectmak i will get an issue up for it today!
