### ISSUE TITLE
[ci/cd] Automate release of project

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKET.js#13]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a developer, I need to automate the release process so that it's clear what is in each release.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
When we do a release, it's important to be clear about what has been added, changed, deleted, or deprecated.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No release automation.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Have release automation including versioning, release notes, and deploying a package to npm.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Look at https://github.com/semantic-release/semantic-release as a first option in automating this process. Here is another helpful reference, https://docs.travis-ci.com/user/deployment/npm

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- Semantic versioning implemented
- Release note automatic generation
- Deploy package to npm
- Test and verify the solution works

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by pelsasser** [comment]
looks like this is partially completed by 3613b0b0f9809e37b31a2f02829b73e34c6fc740 - will leave open for reference on release notes, etc.

**Comment by pelsasser** [comment]
closing ticket for @rojosnow to create ticket for just automated release notes since rest of this is now implemented.
