### ISSUE TITLE
Create a function that compares the abi to the byte code of the deployed MARKET contract

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/MARKET.js#131]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user I would like to ensure i'm using the latest MARKET contracts that have been deployed.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Currently it's possible to get out of sync with the latest deployed contracts

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Create a function that compares the ABI to the byte code of the deployed contract to ensure they match upon instantiation of MARKET.js

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] If ABI and byte code match instatiate MARKET.js
- [ ] If they don't match return a mismatch error

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by perfectmak** [comment]
Here is another interesting issue. Some quick questions that come to mind about this issue.
I know the ABI are currently accessible on start up, but what about the byte code, where do we get that?
If we are fetching the byte code, then this means this would be an async operation right? If yes, then this mean we would need some sort of async constructor for Marketjs?

**Comment by pelsasser** [comment]
@perfectmak - how is this goin?
