### ISSUE TITLE
approveCollateralDepositAsync should allow a bool flag for conversion to base units if need be.

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#158]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a user of the nice abstractions available in MARKET.js, I do not want to have to worry about the conversion from units to base units for erc20 tokens

### Why Is this Needed?
*Summary*: Make everyone's life easier!

### Description
*Type*: Feature

### Current Behavior
Only accepts base units

### Expected Behavior
accepts base units or units

### Solution
*Summary*: update `approveCollateralDepositAsync` and tests

### Definition of Done
- [ ]  add a isBaseUnits flag to the `approveCollateralDepositAsync` function 
- [ ]  add needed logic for conversion from units to base units if isBaseUnits is false
- [ ] add tests

**Comment by perfectmak** [comment]
@pelsasser one quick question with the implementation of this: 
When converting to baseUnit, is it okay to assume that the ERC20 token has its base unit decimal set to: `uint8 public constant decimals = 18`? If so, then this is straightforward.

Many ERC20 tokens usually set this as their baseUnit.

**Comment by pelsasser** [comment]
@perfectmak - 

I think the real problem here is that the decimal places aren't standardized, and I am not sure how to deal with that yet.  18 is certainly the most common, but for the tokens that aren't 18, there is no guarantee in the erc20 specifications that they have even included the decimals field in their contracts.

https://theethereum.wiki/w/index.php/ERC20_Token_Standard

So we could attempt to check the ERC20 to see if it has the decimals field, if it does great, if not default to 18.  However, there are probably still some tokens out there in which that would fail for.

**Comment by perfectmak** [comment]
@pelsasser sounds like a plan. I'll follow this approach.
