### ISSUE TITLE
Error handling when _getContractSetByMarketContractAddressAsync is handed a bad address

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#159]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a user, error messaging is key to debugging

### Why Is this Needed?
*Summary*: Better errors

### Description
*Type*: Bug

### Current Behavior
Recently, we attempted to call a function in market.js with the wrong MarketContract address using this code from the dApp
```
marketjs.approveCollateralDepositAsync(
    simExchange.contract.MARKET_COLLATERAL_POOL_ADDRESS,
    new BigNumber(amount.number),
    txParams,
    (err, res) => {
      console.log('WE ARE HERE', err, res);
      if (err) {
        console.error('fing error', err);
      } else {
        return web3.eth.getTransactionReceiptMined(res).then(function() {
          marketjs
            .depositCollateralAsync(
              simExchange.contract.key,
              new BigNumber(amount.number),
              txParams
            )
            .then(res => {
              showMessage(
                'success',
                'Deposit successful, your transaction will process shortly.',
                5
              );
              return res;
            });
        });
      }
    }
  );
```
the first call to `approveCollateralDepositAsync` was using the CollateralPool adress when we should have been using the MarketContract address, the resulting error message was incredible cryptic.

```
Uncaught (in promise) Error: new BigNumber() not a base 16 number: 
    at raise (bignumber.js:1177)
    at bignumber.js:1165
    at new BigNumber (bignumber.js:212)
    at toBigNumber (utils.js:376)
    at Object.toTwosComplement (utils.js:390)
    at SolidityTypeAddress.formatInputInt [as _inputFormatter] (formatters.js:40)
    at SolidityTypeAddress../node_modules/web3/lib/solidity/type.js.SolidityType.encode (type.js:188)
    at coder.js:91
    at Array.map (<anonymous>)
    at SolidityCoder../node_modules/web3/lib/solidity/coder.js.SolidityCoder.encodeParams (coder.js:90)
    at SolidityFunction../node_modules/web3/lib/web3/function.js.SolidityFunction.toPayload (function.js:92)
    at SolidityFunction../node_modules/web3/lib/web3/function.js.SolidityFunction.sendTransaction (function.js:163)
    at index.es5.js:3162
    at new Promise (<anonymous>)
    at promisify (index.es5.js:3161)
    at DeferredTransactionWrapper.send (index.es5.js:3068)
    at OraclizeContractWrapper.<anonymous> (index.es5.js:13766)
    at step (index.es5.js:69)
    at Object.next (index.es5.js:50)
    at fulfilled (index.es5.js:40)
raise @ bignumber.js:1177
(anonymous) @ bignumber.js:1165
BigNumber @ bignumber.js:212
toBigNumber @ utils.js:376
toTwosComplement @ utils.js:390
formatInputInt @ formatters.js:40
./node_modules/web3/lib/solidity/type.js.SolidityType.encode @ type.js:188
(anonymous) @ coder.js:91
./node_modules/web3/lib/solidity/coder.js.SolidityCoder.encodeParams @ coder.js:90
./node_modules/web3/lib/web3/function.js.SolidityFunction.toPayload @ function.js:92
./node_modules/web3/lib/web3/function.js.SolidityFunction.sendTransaction @ function.js:163
(anonymous) @ index.es5.js:3162
promisify @ index.es5.js:3161
DeferredTransactionWrapper.send @ index.es5.js:3068
(anonymous) @ index.es5.js:13766
step @ index.es5.js:69
(anonymous) @ index.es5.js:50
fulfilled @ index.es5.js:40
```

### Expected Behavior
A nice error messaging saying the supplied address in NOT a market contract

### Reproduction
See above code, attempt calling `approveCollateralDepositAsync` with an address of a collateral pool

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Create some check to ensure the address the user supplied has a MarketContract deployed to it! Maybe by checking the byte code at the address vs the abi

### Definition of Done
- [ ] create check that would have caught this error
- [ ] modify error message so the user understands the issue
- [ ] add tests!

**Comment by perfectmak** [comment]
Haaa... Okay, @pelsasser that makes sense. So `isMarketContractAddress()` would be kinda like an abstract method on the base ContractWrapper that needs to be implemented by each sub-classes for proper validation. Thanks, that make things easier. 

I'll follow this approach and revert with a PR as soon as possible.
