### ISSUE TITLE
[Error MSGs]  add more information to error messages.

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#165]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a user, I want to know which side needs more collateral when I get an Insufficient Collateral Error

### Why Is this Needed?
*Summary*: Hard to know if you need more collateral our your counterparty does. 

### Description
*Type*: Feature

### Current Behavior
Error message looks like 'INSUFFICIENT_COLLATERAL_BALANCE'

### Expected Behavior
Error message looks like 'INSUFFICIENT_COLLATERAL_BALANCE_MAKER' or 
'INSUFFICIENT_COLLATERAL_BALANCE_TAKER'

### Reproduction
call traderOrderAsync with not enough collateral 

### Solution
*Summary*: Add more descriptive error messages

### Definition of Done
- [ ] updated all error messages that can pertain to only one person with MAKER or TAKER appended
- [ ] update all tests / create new tests.

**Comment by perfectmak** [comment]
This came to my mind earlier, when doing some validation. It can handle it too.
