### ISSUE TITLE
getUserPositionsAsync should return empty array instead of Error when user has no position

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#167]
Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a developer, I would like to reserve errors for special error cases

### Why Is this Needed?
*Summary*: A user have no pos is not an error, but an expected state.

### Description
*Type*: Bug

### Current Behavior
getUserPositionsAsync and getUserPositionAsync return errors when a user has no position

### Expected Behavior
getUserPositionsAsync and getUserPositionAsync return empty arrays or 0 

### Solution
*Summary*: Updated these two functions

### Definition of Done
- [ ] modify return values of getUserPositionsAsync and getUserPositionAsync
- [ ] update tests

**Comment by perfectmak** [comment]
@pelsasser I have a question about this.
The UserPosition is actually an array of BigNumber (`BigNumber[]`) for price and qty, so for the `getUserPositionsAsync() which returns `BigNumber[][]` it is okay to return an empty array of positions, but for getUserPositionAsync() which returns a `BigNumber[]` wouldn't it be weird to return an empty array, I was thinking of return a null value instead so it would be easier to check if there is a position. Is this okay?
