### ISSUE TITLE
Follow standard variable name for expiration timestamp

### ISSUE THREAD

**Issue by eswarasai** [MARKETProtocol/MARKET.js#171]
### Description
Currently we use both the variable names `expirationTimeStamp` and `expirationTimestamp` across `MAREKT.js` for depicting expiration timestamp. Instead we should be only using one of the above throughout the codebase across all the repos to avoid inconsistency.

*Type*: Maintenance

### Definition of Done
- [x] Refactor to use the variable name `expirationTimestamp`

**Comment by eswarasai** [comment]
@pelsasser @perfectmak -- Need your inputs here on how to proceed on this. It's super confusing to have both these variables spread throughout the repo.

**Comment by pelsasser** [comment]
Well, I guess technically timestamp is one word, so following strict camel case would be expirationTimestamp

**Comment by eswarasai** [comment]
@pelsasser -- Yep. That's what I've initially followed while setting up the `MARKET.js` repo but looks like in the `MARKETProtocol` repo we're using `expirationTimeStamp`. Hence the confusion.
Ref: https://github.com/MARKETProtocol/MARKETProtocol/blob/develop/contracts/MarketContract.sol#L110
