### ISSUE TITLE
[metadata] Add collateralTokenName to getContractMetaDataAsync()

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKET.js#174]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a developer, I need to get the collateral token name so I can use this within my application.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Return the collateralTokenName when getting the metadata about a contract.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
`collateralTokenName` is not returned as part of `getContractMetaDataAsync()`.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Make is so!

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
We're still working on this.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- `collateralTokenName` is returned as part of `getContractMetaDataAsync()`.
- Don't break anything. ;)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by perfectmak** [comment]
This is straight forward, @rojosnow are there currently any blockers to this?

**Comment by pelsasser** [comment]
no blockers!
