### ISSUE TITLE
[Bug] fs.readFileSync is not a function

### ISSUE THREAD

**Issue by eswarasai** [MARKETProtocol/MARKET.js#176]
### Description
Currently, when trying to initialize `MARKET.js` within `dApp` connect to local truffle, throws an error saying `fs.readFileSync` is not a function. This is because `fs` is unavailable in browser mode for security reasons. This is being used currently in the `_verifyContracts()` method. 

*Type*: Bug

### Solution
Workaround would be to skip the check for local truffle provider

### Definition of Done
- [x] Be able to initialize `MARKET.js` using local truffle

**Comment by eswarasai** [comment]
@perfectmak @travisdmathis -- Would there be any issue with the proposed solution for this bug?

cc: @MARKETProtocol/core

**Comment by pelsasser** [comment]
It is also used for truffle in `_updateConfigFromArtifacts`.

We could skip the verification for truffle, but this does open us back up to the mismatch issues when using truffle.  Not sure how else to deal with that however given the current contstraints.

**Comment by eswarasai** [comment]
@pelsasser -- Yes. For the `_updateConfigFromArtifacts()`, I've bypassed it by ensuring `dApp` is passing all the addresses in the `config`. But for verification of the artifacts, I'm not really sure how we can solve this to handle all the use cases. Hence opened it up for discussion.

**Comment by pelsasser** [comment]
I don't think there is any option here.

If your using truffle, and market.js in a browser application, you aren't going to be able to verify the contracts.  It would be nice if we could create a switch, so using truffle for local dev / testing in MARKET.js could still perform the verification, but it would be bypassed for browser use.  

Besides some environment variable, only thing I can think of is adding a constructor argument to Market() `isVerifyContracts` to by pass if desired.

**Comment by eswarasai** [comment]
@pelsasser -- Yeah. I think that's much better solution to add `verifyContracts` boolean to the `MARKETProtocolConfig`. Let me quickly create a PR for this and call it done. Thanks!
