### ISSUE TITLE
[static] Create static versions of `getContractMetaDataAsync()` and `getAddressWhiteListAsync()`

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKET.js#177]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a developer, I need the ability to call static methods in `MARKET.js` so that I don't have a dependency on web3.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Having static methods help with unit testing.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
Static methods only exist for getOrderHash() and isValidSignature()

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Ability to call static methods for getContractMetaData() and getAddressWhiteList()

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Add static methods for getContractMetaDataAsync() and getAddressWhiteListAsync()

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- Add static method getContractMetaData()
- Add static method getAddressWhiteList()
- Determine if the `Async` versions of the methods should be removed
- Don't break any tests! ;)

**Comment by pelsasser** [comment]
@rojosnow - this unfortunately is not possible with current architecture / class structure.

**Comment by rojosnow** [comment]
@pelsasser I wasn't sure so I thought I would create the issue for discussion tomorrow. Both methods?

**Comment by pelsasser** [comment]
correct, both methods.  I am pretty sure your use case is to avoid web3, so in theory, we could make these functions static, but would require the caller to pass in the web3 object directly, so I don't think it helps you

**Comment by rojosnow** [comment]
You got it. Trying to be more test friendly.
