### ISSUE TITLE
[logging] SPIKE: Error handling and logging in MARKET.js

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKET.js#179]
### User Story
[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a developer, I need to access `MARKET.js` logs and error messages so that I can debug issues quickly.

### Why Is this Needed?
[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*:
We need better logging and error messages with `MARKET.js` since there are many points of failure and it's hard to know where things go wrong.

### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
No or little error/logging information is provided by `MARKET.js`

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Add the necessary error and logging information to `MARKET.js`

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Use this SPIKE issue to discuss the implementation of error handling and logging in `MARKET.js`

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- Determine the issues needed to implement a first iteration of error handling and logging in `MARKET.js`.

**Comment by rojosnow** [comment]
@travisdmathis @pelsasser @eswarasai @nitinrgupta @perfectmak As a result of today's call, I created this SPIKE discussion issue to start a conversation around error handling and logging for `MARKET.js`. As a result of the discussion, I'd like to identify and enter the necessary issues to get us to a first iteration.

We'll need to at least answer the following questions:

- What errors get logged, messaging/description, and severity levels?
- Where do the logs get stored?
- How are they accessed?
- Who are they available to?

Any other questions we need to answer?

**Comment by perfectmak** [comment]
@rojosnow before try and propose some answers to the questions, isn't this issue also related to #23 ?

**Comment by rojosnow** [comment]
@perfectmak It is. This issue is to discuss the solution for the first iteration. #23 probably needs to be an epic to track the work. There will be a few issues to implement whatever we come up with.
