### ISSUE TITLE
[api] MARKET order management (fills/cancels) by third party order book hosts

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKET.js#20]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a third party order book host, I need to manage fills and cancelations of orders so that the order book is updated and accurately reflects available orders.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*: Third-party order book hosts will be responsible for removing completely filled or completely canceled orders from their order books. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
No api functionality exists.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Third-party order book hosts will be responsible for removing completely filled or completely canceled orders from their order books. Orders can be canceled by setting an `expirationTimeStamp` or by calling the function `cancelOrder` at any time.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Third parties managing order books need to understand the status of orders: fills, cancels, expiration.

Here is the order flow as an additional reference, https://docs.marketprotocol.io/#market-js.

Ox references on order watching:
https://0xproject.com/docs/0x.js#orderWatcher
https://github.com/0xProject/0x-monorepo/blob/master/packages/0x.js/src/order_watcher/expiration_watcher.ts

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- Use TypeScript for your code and the supporting typedefs
- Your code should be in the appropriate defined module depending on its function. For example, order and settlement related functions go in the `Order` or `Settlement` module
- Documenting your code is a must since docs are generated from your comments...no comments, no docs.. ;)
- Write/pass tests

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by pelsasser** [comment]
decomposing this into more manageable chunks. Closing for now.
