### ISSUE TITLE
[api] MARKET manage collateral

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKET.js#21]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a trading participant (maker/taker), I need the ability to manage my collateral so that I can trade contracts.

### Why Is this Needed?
*Summary*:
Trading participants (maker/taker) need to manage their collateral for trading.  This is any arbitray ERC20 (wrapped ETH, a stable coin, etc).

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
Not implemented.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Allow the trading participant (maker/taker) to manage their collateral for trading.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
This issue adds the ability to manage collateral for trading. There are several steps in funding a Market contract. When a Market contract is created, the Market collateral pool contract is also created but not funded. Market collateral pool contract holds collateral balances, user balances, and open positions. 

A trading participant, maker in this case, must deposit collateral into their trading account. This is in the form of ERC20. Once deposited, the funds are used to collateralize an order. When the order is filled by the taker, the same process happens...deposit funds into a trading account and collateralize the other side of the order.

Once the trading ends (trade out, expires/settles, cancels), collateral needs to be recaptured and placed back into the appropriate trading account. Finally, a maker/taker need the ability to withdraw funds from their trading account.

Here is the order flow as an additional reference, https://docs.marketprotocol.io/#market-js.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- Deposit collateral into a trading account.
- Withdraw collateral from a trading account.
- Use a trading account and fund a collateral pool.
- Recapture collateral into a trading account.
- Use TypeScript for your code and the supporting typedefs.
- Your code should be in the appropriate defined module depending on its function. For example, collateral related functions go in the `Collateral` module
- Documenting your code is a must since docs are generated from your comments...no comments, no docs.. ;)
- Write/pass tests

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by pelsasser** [comment]
@rojosnow I update the issues slightly here. I think if we can stub out the function calls someone should be able to pick this up.

**Comment by rojosnow** [comment]
@pelsasser Good. This answers one of the questions I had about the types of collateral.
