### ISSUE TITLE
[types] Integrate @marketprotocol/types into MARKET.js

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#25]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

As a developer I want to leverage published packages vs create type defs on demand

### Why Is this Needed?

*Summary*: helps with dependencies and versions

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
types defs are generated

### Expected Behavior
type defs are accessed via a npm package

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
removed all type def generations from this repo and use the @marketprotocol/types package. 

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by eswarasai** [comment]
Done: https://github.com/MARKETProtocol/MARKET.js/commit/dc3c0273419c6177448811b2df487f670e44e9f2
