### ISSUE TITLE
[Discussion] file naming standards for MARKET.js

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#43]
We are kind of all over the place with capitalization, lets standardize this.

Any strong convictions one way or the other here? @rojosnow @eswarasai

**Comment by rojosnow** [comment]
@pelsasser I did some doc block clean up in the latest feature branch commit since that looked a bit messy too. The `Market.ts` and `Contract.ts` is a bit better organized on that front.

Are you talking about making sure we're using camelcase? I think that's what we've been following so far.
