### ISSUE TITLE
[Truffle] migrations fail with truffle >=4.1.12

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#47]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

As a user I would like migrations to work!

### Why Is this Needed?
*Summary*: For testing and development environments

### Description
*Type*: Bug

Currently we do not enforce the truffle version very well and the new build of truffle fails `migrate --reset`

### Current Behavior
Migrations fail!

### Expected Behavior
Migrations should work
truffle version is enforced!

### Reproduction
`sudo npm install -g truffle`
and then attempt `migrate --reset`

### Definition of Done
- [ ] Fix issues with using truffle 4.1.12
- [ ] Enforce truffle version and add info to README

### Additional info
```
Running migration: 2_deploy_contracts.js
/usr/local/lib/node_modules/truffle/build/cli.bundled.js:60300
  throw new Error("Could not find artifacts for " + import_path + " from any sources");
  ^

Error: Could not find artifacts for market-solidity/contracts/libraries/MathLib from any sources
    at Resolver.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:60300:9)
    at Object.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70096:36)
    at ResolverIntercept.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:207523:32)
    at /mnt/c/Users/ASUS/MARKET.js/migrations/2_deploy_contracts.js:1:27
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:104201:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by eswarasai** [comment]
@pelsasser -- I just tried to run migrations using `truffle@4.1.12` and everything seemed to work fine for me. From the additional info error message, it looked like the node module `market-solidity` might not have been installed at the prior of running migrations. Let me know if I'm missing something here.

**Comment by pelsasser** [comment]
@eswarasai - unfortunately, market-solidity was definitely installed.  If you try this on a clean install (no /build folder) 4.4.12 will fail

**Comment by KennethAshley** [comment]
@eswarasai @pelsasser let me know if that solved the issue for you guys!

**Comment by pelsasser** [comment]
@KennethAshley - LGTM
