### ISSUE TITLE
[traderOrder] Validate traderOrder prior to creating transaction as much as possible

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#61]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

As a user, I would hope that all possible validations are done off chain, prior to creating an on chain transaction that is going to cost gas even if it reverts / fails

### Why Is this Needed?

*Summary*: Help with validation and error messaging.

### Description

*Type*: Feature

### Solution
*Summary*: validate as much as possible before calling traderOrder

### Definition of Done

Create functionality to validate 

- [ ] maker and taker are both enabled mktTokenContract.isUserEnabledForContract() if not return MarketError.UserNotEnabledForContract()
- [ ] Ensure both maker and taker have sufficient MKT balances for any fess
- [ ] Ensure both maker and taker have sufficient collateral balances in order to collateralize trade.
- [ ] Order singature is valid
- [ ] Taker address as defined in the order is null, or is the caller of `traderOrder`
- [ ] The order is not expired
- [ ] The order qty and the fill qty are the same sign
- [ ] The order is not fully filled or fully cancelled
- [ ] Tests for each of these scenarios with correct MarketError object returned

### Additional Information
0x implementation of a similar functionality can be found [here](https://github.com/0xProject/0x-monorepo/blob/master/packages/0x.js/src/utils/order_validation_utils.ts) and [here](https://github.com/0xProject/0x-monorepo/blob/master/packages/0x.js/src/utils/exchange_transfer_simulator.ts)

**Comment by perfectmak** [comment]
Or I could work on this first @pelsasser depending on which one is of higher priority between this and #67 ,

**Comment by pelsasser** [comment]
@perfectmak - @StevenJNPearce is gonna tackle this one.  Looks like I need to get more worked staked out! thanks guys!!!

**Comment by pelsasser** [comment]
@StevenJNPearce - I updated the @marketprotocol/types pkg in https://github.com/MARKETProtocol/MARKET.js/commit/4c95eb4ebbaeaafd8ef268977e0601787012ed81 to now have a MarketError object if that helps you here for returning errors
