### ISSUE TITLE
[Tests]  Issues with second test run after migrations

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKET.js#74]
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a dev, ideally I don't want have to redeploy (run `migrate --reset`) each time I want to run tests.

### Why Is this Needed?

*Summary*: quicker development

### Description

*Type*: Feature

### Current Behavior
Some tests are dependent on a clean migration

### Expected Behavior
tests cleanup or are flexible enough to allow a non clean environment (IE collateral already deposited, etc)

### Reproduction
run migrations, npm run test, and then npm run test again

using docker 

```
export TRUFFLE_DEVELOP_HOST=marketjs
export TRUFFLE_DEVELOP_PORT=9545
docker-compose up -d
docker-compose exec marketjs npm install
docker-compose exec marketjs truffle migrate
docker-compose exec marketjs env TRUFFLE_DEVELOP_HOST="$TRUFFLE_DEVELOP_HOST" npm run test:prod
docker-compose exec marketjs env TRUFFLE_DEVELOP_HOST="$TRUFFLE_DEVELOP_HOST" npm run test:prod
```

### Solution
*Summary*: Modify tests to clean up after themselves!

### Definition of Done
run migrations, npm run test, and then npm run test again and everything passes!

**Comment by cryptomental** [comment]
Hi @pelsasser I solved it here https://github.com/cryptomental/MARKET.js/commit/0542e18da37e87b7edaf5036154c140e611d017c

I branched off the OrderValidation test for RemainingFillableCalc work.

will later clean up and open a PR to OrderValidation as well (likely tomorrow as I will be travelling today afternoon).

Difference to the original is:

- extracted common parts
- before each test case transfer collateral 
- after each test case return the collateral back to maker and taker

I also removed a few unused imports and variables, for example collateralPool was defined and assigned but never used and renamed maker/taker to makerAddress/takerAddress to make it consistent with other variables.

Additionally what I came up with is that we could think of renaming getUserAccountBalanceAsync() and re-implementing  getUserAccountBalanceAsync().

MARKET.js API provides depositCollateralAsync(), withdrawCollateralAsync() .

How about  of renaming getUserAccountBalanceAsync()  to getCollateraBalanceAsync() ?

Function getUserAccountBalanceAsync() should return what is available in the user's account and not what was deposited to the collateral pool.

**Comment by pelsasser** [comment]
@cryptomental - thanks for the hard work on all of this!  Some great progress is being made in this repo.

> Additionally what I came up with is that we could think of renaming getUserAccountBalanceAsync() and re-implementing getUserAccountBalanceAsync().
> 
> MARKET.js API provides depositCollateralAsync(), withdrawCollateralAsync() .
> 
> How about of renaming getUserAccountBalanceAsync() to getCollateraBalanceAsync() ?
> 
> Function getUserAccountBalanceAsync() should return what is available in the user's account and not what was deposited to the collateral pool.

I think this does make sense in order to keep things a bit more consistent naming, but I am a tad confused on the last sentence here.  Can we connect on discord about it today?

**Comment by cryptomental** [comment]
Hi @pelsasser sorry for the confusion you can skip the comment. I am just looking through your yesterday's collateral calc commits. I was totally into the football match yesterday and did not check emails.

**Comment by pelsasser** [comment]
@cryptomental - sounds good - some of the naming suggestions do resonate with me.  Some refactoring of the names is something I certainly open to.

**Comment by pelsasser** [comment]
@cryptomental any chance you can open a PR for the test fix? would love to get that into the hands of the other devs working on this since its a bit bothersome.

**Comment by cryptomental** [comment]
Hi, I didn't have time until now, will start right away and open a PR today.

**Comment by cryptomental** [comment]
PR opened, works like a charm on my local setup.
