### ISSUE TITLE
[api] MARKET order verification

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKET.js#9]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a third party hosting an order book, I need the ability to verify an order before placing it in my order book so I know it can be traded.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*: Since most order management is performed off-chain, order books need to verify orders, including signatures, funding in the MARKET Contract, and locked MKT tokens. Once these verifications are complete, the order can be listed in an order book.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
No verification functionality.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Provide verification functionality to include

- Signature verification
- Verifying sufficient funding in the MARKET Contract for the maker's address
- Validating user has locked MKT to allow for access to trading the specified MARKET Protocol smart contract.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Here is the order flow as an additional reference, https://docs.marketprotocol.io/#market-js.

Use the appropriate smart contract functions to verify a signature and collateral requirements (ETH & MKT tokens). Look at [CollateralToken.sol](https://github.com/MARKETProtocol/MARKETProtocol/blob/master/contracts/tokens/CollateralToken.sol), [MarketCollateralPool.sol](https://github.com/MARKETProtocol/MARKETProtocol/blob/master/contracts/MarketCollateralPool.sol), [CollateralToken.ts](https://github.com/MARKETProtocol/types/blob/develop/types/CollateralToken.ts), and [MarketCollateralPool.ts](https://github.com/MARKETProtocol/types/blob/develop/types/MarketCollateralPool.ts) for details.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- Use TypeScript for your code and the supporting typedefs
- Your code should be in the appropriate defined module depending on its function. For example, collateral and token related functions go in the `Collateral` module
- Documenting your code is a must since docs are generated from your comments...no comments, no docs.. ;)
- Write/pass tests

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by eswarasai** [comment]
@pelsasser -- What's the status on this? I'm not really sure what needs to be done here.

**Comment by pelsasser** [comment]
We should package a single function that allows for an order to be checked to ensure.

1) A user is enabled to trade the contract (has locked sufficient MKT)
2) The maker has sufficient balance in the CollateralPool if the order is filled
3) The order hasn't expired. 
4) The signature is valid

**Comment by perfectmak** [comment]
I believe Market.js already has most (if not all of the functionalities required here) with `tradeOrderAsync()` now performing most of these checks before allowing a user to trade and the new `OrderStateWatcher` #124  which allows for subscribing to watch orders for validity.

Or is there something else not covered?

**Comment by eswarasai** [comment]
@perfectmak -- Yes. Except for 1, I'm pretty sure rest all other validations are in place. We're awaiting on confirmation from @pelsasser regarding 1 in order to close out this issue.

**Comment by perfectmak** [comment]
@eswarasai, For 1, isn't that what the `isUserEnabledForContract()` checks [here](https://github.com/MARKETProtocol/MARKET.js/blob/develop/src/contract_wrappers/ContractWrapper.ts#L153) are for?

But let's wait for @pelsasser, somethings might still be missing.

**Comment by pelsasser** [comment]
this looks completed to me.

I think we could do some clean up of code however to re-use the utility functions that @perfectmak created into traderOrderAsync so we only have that code in once place, but otherwise this all looks good.  Closing issue for now.
