### ISSUE TITLE
[api] Create functionality to allow querying of a user's open position and net position

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/MARKET.js#94]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a user, I need the ability to see my open positions so that I know my exposure to the market.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Users need to see their open positions

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
Open positions are not shown.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Users can see their open positions.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
create functions that help with querying a users open position for a given contract.

### Definition of Done

- [ ] Implement the functionality in MARKET.js using the existing patterns for that project.
- [ ] implement getUserNetPos wrapper to return a user's net position
- [ ] implement getUserPositions to return array of all open positions 
- [ ] Provide good comments/docs on how the functionality works.
- [ ] Write/pass tests for the added functionality.

**Comment by vyomshm** [comment]
@rojosnow I believe functionality is same as described here - https://github.com/MARKETProtocol/MARKET.js/issues/100 . PR- #115 resolves this.

**Comment by rojosnow** [comment]
@vyomshm You're right, thanks!
